### ISSUE TITLE
Packer fails "Parallels Virtualization SDK is not installed" when it is installed

### ISSUE THREAD

**Issue by jhgorse** [Parallels/packer-plugin-parallels#36] opened 2022-03-30 23:05 UTC
When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Overview of the Issue

Packer fails to detect the installed Parallels Virtualization SDK.

```
joe.gorse@Joes-MacBook-Pro bento % ls /Library/Frameworks/ParallelsVirtualizationSDK.framework
Headers				Libraries			ParallelsVirtualizationSDK	Resources			Versions
```

```
joe.gorse@Joes-MacBook-Pro bento % packer build -only=parallels-iso packer_templates/ubuntu/ubuntu-20.04-arm64.json
parallels-iso: output will be in this color.

Build 'parallels-iso' errored after 1 millisecond 777 microseconds: Failed creating Parallels driver: Parallels Virtualization SDK is not installed

==> Wait completed after 1 millisecond 817 microseconds

==> Some builds didn't complete successfully and had errors:
--> parallels-iso: Failed creating Parallels driver: Parallels Virtualization SDK is not installed

==> Builds finished but no artifacts were created.
```

#### Reproduction Steps

```
brew install vagrant
vagrant plugin install vagrant-parallels

git clone https://github.com/chef/bento && cd bento
# sudo gem install mixlib-shellout
packer build -only=parallels-iso packer_templates/ubuntu/ubuntu-20.04-arm64.json
```

### Plugin and Packer version

packer --version
1.8.0

### Simplified Packer Buildfile

https://github.com/chef/bento/blob/main/packer_templates/ubuntu/ubuntu-20.04-arm64.json

### Operating system and Environment details

macOS Monterey
2022 Macbook Pro
m1 aarch64

### Log Fragments and crash.log files

```
2022/03/31 11:07:09 Build debug mode: true
2022/03/31 11:07:09 Force build: false
2022/03/31 11:07:09 On error: ask
2022/03/31 11:07:09 Debug enabled, so waiting for build to finish: parallels-iso
2022/03/31 11:07:09 Starting build run: parallels-iso
2022/03/31 11:07:09 Running builder: parallels-iso
2022/03/31 11:07:09 [INFO] (telemetry) Starting builder parallels-iso
2022/03/31 11:07:09 [INFO] (telemetry) ending parallels-iso
2022/03/31 11:07:09 ui error: Build 'parallels-iso' errored after 3 milliseconds 544 microseconds: Failed creating Parallels driver: Parallels Virtualization SDK is not installed
2022/03/31 11:07:09 Waiting on builds to complete...
2022/03/31 11:07:09 ui:
==> Wait completed after 3 milliseconds 985 microseconds
2022/03/31 11:07:09 machine readable: error-count []string{"1"}
2022/03/31 11:07:09 ui error:
==> Some builds didn't complete successfully and had errors:
2022/03/31 11:07:09 machine readable: parallels-iso,error []string{"Failed creating Parallels driver: Parallels Virtualization SDK is not installed"}
2022/03/31 11:07:09 ui error: --> parallels-iso: Failed creating Parallels driver: Parallels Virtualization SDK is not installed
2022/03/31 11:07:09 ui:
==> Builds finished but no artifacts were created.
2022/03/31 11:07:09 [INFO] (telemetry) Finalizing.
2022/03/31 11:07:09 waiting for all plugin processes to complete...
2022/03/31 11:07:09 /opt/homebrew/Cellar/packer/1.8.0/libexec/bin/packer: plugin process exited
2022/03/31 11:07:09 /opt/homebrew/Cellar/packer/1.8.0/libexec/bin/packer: plugin process exited
2022/03/31 11:07:09 /opt/homebrew/Cellar/packer/1.8.0/libexec/bin/packer: plugin process exited
```

**Comment by jhgorse** [comment] 2022-03-31 13:27
https://github.com/hashicorp/packer-plugin-parallels/blob/319e74d5fbe3bfa2c54b1a4abcff16931b090ea7/builder/parallels/common/driver.go#L78

```
	cmd := exec.Command("/usr/bin/python3", "-c", `import prlsdkapi`)
	err := cmd.Run()
```

These backticks look offensive to me, but is a golang thing for escaping strings.

Python3 does not see prlsdkapi.

**Comment by holgerde** [comment] 2022-03-31 14:01
I'm having the same problem. I installed parallels and parallels-virtualization-sdk with homebrew and it used to work just fine, tried to build a new box today and get the same error. Reinstalled parallels, parallels-virtualization-sdk and packer but still get the same error. The license of Parallels looks fine as well.

**Comment by jhgorse** [comment] 2022-03-31 14:21
I added the path to PYTHONPATH

`export PYTHONPATH=/Library/Frameworks/ParallelsVirtualizationSDK.framework/Versions/9/Libraries/Python/3.7`

```
joe.gorse@Joes-MacBook-Pro bento % python3 -c "import prlsdkapi"
joe.gorse@Joes-MacBook-Pro bento % which python3
/opt/homebrew/bin/python3
joe.gorse@Joes-MacBook-Pro bento % /usr/bin/python3 -c "import prlsdkapi"
joe.gorse@Joes-MacBook-Pro bento % echo $?
0
```

Both work fine. But `packer` does not respect the PYTHONPATH.

**Comment by jhgorse** [comment] 2022-03-31 14:48
I have no idea what `packer` is doing. I cannot reproduce it's failure.

Walking through it's steps, I see the SDK path but it is not found by `packer`:
```
joe.gorse@Joes-MacBook-Pro bento % /usr/bin/python3
Python 3.8.9 (default, Feb 18 2022, 07:45:33)
[Clang 13.1.6 (clang-1316.0.21.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.path
['', '/Library/Frameworks/ParallelsVirtualizationSDK.framework/Versions/9/Libraries/Python/3.7', '/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python38.zip', '/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8', '/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/lib-dynload', '/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages']
>>>
```

What next?

**Comment by jhgorse** [comment] 2022-03-31 16:51
Packer updated their config files. Use the hcl2 converter. Use this example: https://github.com/hashicorp/packer-plugin-parallels/blob/main/example/build.pkr.hcl

Add this to your config:

```
packer {
  required_plugins {
    parallels = {
      version = ">= 1.0.0"
      source  = "github.com/hashicorp/parallels"
    }
  }
}
```

gl hf

**Comment by jhgorse** [comment] 2022-03-31 17:01
Related to, blocked by, https://github.com/chef/bento/issues/1364

**Comment by holgerde** [comment] 2022-04-01 12:07
Adding the required_plugins section to the Packer file did not solve the problem for me. (Did a packer init before packer build).

**Comment by jhgorse** [comment] 2022-04-01 15:49
Did you convert to HCL? I was unable to get the legacy JSON to work or documentation supporting it's specification in the new environment.

**Comment by holgerde** [comment] 2022-04-04 07:33
Yes, the Packer file was HCL to begin with.

**Comment by BytesGuy** [comment] 2022-04-16 19:59
I am still having to use the `export PYTHONPATH=/Library/Frameworks/ParallelsVirtualizationSDK.framework/Versions/9/Libraries/Python/3.7` method to get builds to work. I'm guessing it can only be resolved by an update to the SDK from Parallels? It was working fine before macOS 12.3 so I guess something to do with the Python changes Apple made knocked it out of whack

**Comment by jhgorse** [comment] 2022-04-17 12:45
Did you guys try the sample hcl file above as sanity check?

If the sample works, it's your hcl file. If the sample does not work, it's your setup. Good luck.

**Comment by undefynd** [comment] 2022-04-21 22:59
#35 
 This pull request will fix the issue, the problem is that there is no new release since it got merged.
 Since I had the same issue I decided to build the parallels-plugin for packer from source and then it worked.

**Comment by Baune8D** [comment] 2022-04-22 13:14
@undefynd It seems to be included in the release here: https://github.com/hashicorp/packer-plugin-parallels/releases/tag/v1.0.1

**Comment by yoonjs2** [comment] 2022-09-14 04:14
The problem recurring after upgrade to:
intel x86
python3.9 (apple)
packer: 1.8.3
parallels-desktop: 18.0.2
packer-plugin-parallels: 1.0.3

I found solution: create symlink to missing prlsdkapi.pth (ref: https://forum.parallels.com/threads/failed-creating-parallels-driver-parallels-virtualization-sdk-is-not-installed.357040/)
```
sudo ln -s /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/prlsdkapi.pth /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages/prlsdkapi.pth
```

It seems Parallels should update their virtualization SDK to respect new latest python3 path.
Anyone knows github repository url for parallels virtualization SDK?

**Comment by spencerhakim** [comment] 2022-10-15 19:02
Hit this issue today. Reinstalling the Parallels SDK didn't fix it, nor did creating the symlink suggested above, but `PYTHONPATH=/Library/Frameworks/ParallelsVirtualizationSDK.framework/Versions/10/Libraries/Python/3.7 packer build [...]` did work. Note that the version number in the path increased from `9` to `10` at some point.

Hope this helps anyone else encountering this issue.

**Comment by deric4** [comment] 2022-11-08 14:26
just ran into this after upgrading from macos12 -> macos13 _before_ upgrading parallels 17 -> 18. 

Some additional info that might help others.

* the path that the `.pth` file needs to be linked to depends on the major.minor version of python that lives at `/usr/bin/python3` (since this is hardcoded in the packer-plugin)

    Usually, this is the python that gets installed after running `xcode-select --install`. for macOS 12 this was **python3.8**, but after upgrading to macOS 13, I had to re-run `xcode-select --intsall` which upgraded `/usr/bin/python3` to **python3.9**

 * Determining which paths to use

    Since the packer-plugin has `/usr/bin/python3` hardcode and we can't be sure what/where that version of python points to across macOS versions or what will be installed by `xcode-select --install` the "easiest" way to be sure is to run the following:

```console
$ /usr/bin/python3 -m site
sys.path = [
    '<pwd>',
    '/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python39.zip',
    '/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9',
    '/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/lib-dynload',
    '/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages',
]
USER_BASE: '/Users/deric4/Library/Python/3.9' (doesn't exist)
USER_SITE: '/Users/deric4/Library/Python/3.9/lib/python/site-packages' (doesn't exist)
ENABLE_USER_SITE: True
```

The path that includes the `site-packages` dir in `sys.path = [ ... ]` is what you'll want to use.

```shell
$ sudo ln -s /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/prlsdkapi.pth <the path with site-packages dir from previous cmd>
```


---

Since it doesn't seem like Parallels is going to release an installer that will handle this dynamically,  I'd like to propose updating the plugin to either:

* allow for configuring which python executable will be used (not sure if/why `/usr/bin/python3` was needed/chosen)

or 

* or hard coding the sitedir in the plugin.

```python
import site

"""
at least this way the plugin can be bumped if this path ever changes and would
 avoid users from trying to figure out where the need to place the symlink of the .pth file
"""
site.addsitedir('/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages')

import prlsdkapi

...
````

**Closed** 2023-07-27 07:53 UTC
Labels: bug
